const mongoose=require('mongoose');
const patientSchema=new mongoose.Schema({
    name:{
        type:String,
        required:true
    },
    city:{
        type:String,
        required:true
    },
    contact:{
        type:String,
        required:true,
        minlength:10,
        maxlength:10
    },
    age:{
        type:Number,
        default:25,
        required:true
    },
    gender:{
        type:String,
        enum:["male","female","others"],
        required:true
    },
    email:{
        type:String,
        required:true,
        unique:true
    },
    pwd:{
        type:String,
        required:true
    }
});
module.exports=mongoose.model('patient',patientSchema);